# Site settings
title: CH Flooring
description: > # this means to ignore newlines until "baseurl:"
  The most reliable flooring service in New Zealand.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
review-form-url: https://api.staticman.net/v3/entry/github/chflooringnz/chflooringnz.github.io/main

email: chflooringnz@gmail.com
phone: 022-042-9005

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
